/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Graphics2D;
import static java.lang.Math.*;

/**
 *
 * @author CGM-C
 */
public class BresenhamLine extends javax.swing.JFrame {

    /**
     * Creates new form BresenhamLine
     */
    public BresenhamLine()
    {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        jButton1.setText("Draw");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 378, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    public int swap(int a,int dummy)
    {
        return a;
    }
    void BresenLine(int x1,int y1,int x2,int y2,Graphics2D obj)
    {
       
        int k=1;
       int []first=new int[2];
        int []last=new int[2];
        if(x1<x2)
        {
            first[0]=x1;
            first[1]=y1;
            last[0]=x2;
            last[1]=y2;
        }
        else
        {
            first[0]=x2;
            first[1]=y2;
            last[0]=x1;
            last[1]=y1;
        }
        int dx=last[0]-first[0];
        int dy=last[1]-first[1];
        float m=(float)dy/(float)dx;
        if(m<=1&&m>=0)
        {
            last[0]=swap(last[1],last[1]=last[0]);
            first[0]=swap(first[1],first[1]=first[0]);
            k=2;
        }
        else if(m<0&&m>=-1)
        {
            first[1]=-first[1];
            last[1]=-last[1];
            k=3;
        }
        else if(m<-1)
        {
            first[1]=-first[1];
            last[1]=-last[1];
            last[0]=swap(last[1],last[1]=last[0]);
            first[0]=swap(first[1],first[1]=first[0]);
            k=4;
        }
        dx=last[0]-first[0];
        dy=last[1]-first[1];
        int noi=max(abs(dx),abs(dy));
        int neg=2*dy;
        int pos=neg-(2*dx);
        int p=neg-dx;
        int x=first[0];
        int y=first[1];
        obj.drawLine(x, y, x, y);
        for(int i=0;i<noi;i++)
        {
           
           if(p<0)
           {
               p=p+neg;
           }
           else
           {
               p=p+pos;
               y=y+1;
           }
           x=x+1;
          //System.out.println(x+""+y);
          //System.out.println(k);
           switch(k)
           {
               case 1 : obj.drawLine(x, y, x, y); break;
               case 2 : obj.drawLine(y, x, y, x); break;
               case 3 : obj.drawLine(x, -y, x, -y); break;
               case 4: obj.drawLine(y, -x, y, -x); break;
           }
           
        } 
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         Graphics2D obj=(Graphics2D)(jPanel1.getGraphics());
         //obj.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
         BresenLine(90 ,50 , 160, 122,obj);
         BresenLine(90,50,13,122,obj);
         BresenLine( 90 , 50, 90, 195,obj);
         //BresenLine( 13 , 122, 160, 122,obj);
         obj.drawLine(13 , 122, 160, 122);
         BresenLine( 13 , 122, 90, 195,obj);
         BresenLine( 160 , 122, 90, 195,obj);
         BresenLine( 60 , 220, 90, 195,obj);
         BresenLine( 90 , 195, 120, 220,obj);
         obj.drawLine(60 , 220, 120, 220);
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BresenhamLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BresenhamLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BresenhamLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BresenhamLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BresenhamLine().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
