/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Graphics2D;

/**
 *
 * @author CGM-C
 */
public class Transformation extends javax.swing.JFrame {

    /**
     * Creates new form Transformation
     */
    public Transformation() {
        initComponents();
    }
    float rect[][]={{20,30},{20,60},{50,60},{50,30}};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                         

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int tx=Integer.parseInt(jTextField1.getText());
        int ty=Integer.parseInt(jTextField2.getText());
        int i,j;
        translate(tx,ty);
        drawRectangle();
        
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         drawRectangle();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        float sx=Float.parseFloat(jTextField3.getText());
        float sy=Float.parseFloat(jTextField4.getText());
        //int xf=Integer.parseInt(jTextField6.getText());
        //int yf=Integer.parseInt(jTextField7.getText());
        //translate(-xf,-yf);
        int i;
        for(i=0;i<4;i++)
        {
           // rect[i]=translate(tx,ty,rect[i]);
            rect[i][0]=rect[i][0]*sx;
            rect[i][1]=rect[i][1]*sy;
        }
        //translate(-xf,-yf);
        drawRectangle();
        
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        //int xr=Integer.parseInt(jTextField6.getText());
        //int yr=Integer.parseInt(jTextField7.getText());
        int theta=Integer.parseInt(jTextField5.getText());
        
        //translate(-xr,-yr);
        int i;
        float costheta=(float)Math.cos(Math.toRadians(theta));
        float sintheta=(float)Math.sin(Math.toRadians(theta));
        for(i=0;i<4;i++)
        {
            rect[i][0]=(rect[i][0]*costheta)-(rect[i][1]*sintheta);
            rect[i][1]=(rect[i][0]*sintheta)+(rect[i][1]*costheta);
        }
        //translate(xr,yr);
        drawRectangle();
    }                                        

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int i;
        for(i=0;i<4;i++)
        {
            rect[i][1]=-rect[i][1];
           
        }
        drawRectangle();
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int i;
        for(i=0;i<4;i++)
        {
            rect[i][0]=-rect[i][0];
           
        }
        drawRectangle();
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int i;
        float temp;
        for(i=0;i<4;i++)
        {
            temp=rect[i][0];
            rect[i][0]=rect[i][1];
           rect[i][1]=temp;
        }
        drawRectangle();
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int i;
        int shx=Integer.parseInt(jTextField6.getText());
        for(i=0;i<4;i++)
        {
         rect[i][0]=rect[i][0]+(shx*rect[i][1]);
        }
        drawRectangle();
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int i;
        int shy=Integer.parseInt(jTextField7.getText());
        for(i=0;i<4;i++)
        {
         rect[i][1]=rect[i][1]+(shy*rect[i][0]);
        }
        drawRectangle();
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int i;
        int xref=Integer.parseInt(jTextField6.getText());
        int shy=Integer.parseInt(jTextField7.getText());
        for(i=0;i<4;i++)
        {
         rect[i][1]=rect[i][1]+(shy*(rect[i][0]-xref));
        }
        drawRectangle();
    }                                         

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        float sx=Float.parseFloat(jTextField3.getText());
        float sy=Float.parseFloat(jTextField4.getText());
        int xf=Integer.parseInt(jTextField6.getText());
        int yf=Integer.parseInt(jTextField7.getText());
        translate(-xf,-yf);
        int i;
        for(i=0;i<4;i++)
        {
           // rect[i]=translate(tx,ty,rect[i]);
            rect[i][0]=rect[i][0]*sx;
            rect[i][1]=rect[i][1]*sy;
        }
        translate(-xf,-yf);
        drawRectangle();
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int xr=Integer.parseInt(jTextField6.getText());
        int yr=Integer.parseInt(jTextField7.getText());
        int theta=Integer.parseInt(jTextField6.getText());
        
        translate(-xr,-yr);
        int i;
        float costheta=(float)Math.cos(Math.toRadians(theta));
        float sintheta=(float)Math.sin(Math.toRadians(theta));
        for(i=0;i<4;i++)
        {
            rect[i][0]=(rect[i][0]*costheta)-(rect[i][1]*sintheta);
            rect[i][1]=(rect[i][0]*sintheta)+(rect[i][1]*costheta);
        }
        translate(xr,yr);
        drawRectangle();
    }                                         
    public void drawRectangle()
    {
      Graphics2D obj=(Graphics2D)jPanel1.getGraphics();
      obj.translate(187,145);
      obj.drawLine((int)rect[0][0], (int)rect[0][1],(int)rect[1][0], (int)rect[1][1]);
      obj.drawLine((int)rect[1][0], (int)rect[1][1],(int)rect[2][0],(int) rect[2][1]);
      obj.drawLine((int)rect[2][0], (int)rect[2][1],(int)rect[3][0], (int)rect[3][1]);
      obj.drawLine((int)rect[3][0], (int)rect[3][1],(int)rect[0][0], (int)rect[0][1]);
    }
    /**
     * @param args the command line arguments
     */
    public void translate(int tx,int ty)
    {
        int i;
        for(i=0;i<4;i++)
        {
           // rect[i]=translate(tx,ty,rect[i]);
            rect[i][0]=rect[i][0]+tx;
            rect[i][1]=rect[i][1]+ty;
        }
       
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transformation().setVisible(true);
            }
        });
        
        //int rect[][]={{70,200},{70,100},{200,200},{200,100}};
        //rect[0][0]=70;
        /*int A[]=new int[2];
        int B[]=new int[2];
        int C[]=new int[2];
        int D[]=new int[2];*/
        
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration                   
}
